ALTER TABLE user
DROP PRIMARY KEY;

ALTER TABLE user
MODIFY phone CHAR(10);

ALTER TABLE USER
ADD user_id SMALLINT UNSIGNED;

ALTER TABLE user
ADD CONSTRAINT pk_user PRIMARY KEY (user_id);

ALTER TABLE user
MODIFY user_id SMALLINT UNSIGNED AUTO_INCREMENT;
